# Generated by Django 4.1.7 on 2023-04-09 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('access_token_secret', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='twitter_oauth_token',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TwitterAuthToken',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
